SELECT CUSTOMER_NAME,
       ROUND(SUM(SALES),2) AS TOTAL_SALES,
       RANK() OVER (ORDER BY SUM(SALES) DESC) AS RANK_NO,
       DENSE_RANK() OVER (ORDER BY SUM(SALES) DESC) AS DENSE_RANK_NO
FROM SUPERSTORE_RAW
GROUP BY CUSTOMER_NAME;