SELECT REGION,
       CUSTOMER_NAME,
       TOTAL_SALES,
       ROW_NUM
FROM
(
    SELECT REGION,
           CUSTOMER_NAME,
           ROUND(SUM(SALES), 2) AS TOTAL_SALES,
           ROW_NUMBER() OVER
           (
               PARTITION BY REGION
               ORDER BY SUM(SALES) DESC
           ) AS ROW_NUM
    FROM SUPERSTORE_RAW
    GROUP BY REGION, CUSTOMER_NAME
)
WHERE ROW_NUM <= 3
ORDER BY REGION, ROW_NUM;