WITH CUSTOMER_SALES AS
(
    SELECT CUSTOMER_NAME,
           ROUND(SUM(SALES),2) AS TOTAL_SALES
    FROM SUPERSTORE_RAW
    GROUP BY CUSTOMER_NAME
)
SELECT CUSTOMER_NAME,
       TOTAL_SALES
FROM CUSTOMER_SALES
ORDER BY TOTAL_SALES DESC
FETCH FIRST 10 ROWS ONLY;