WITH CUSTOMER_REGION_SALES AS
(
    SELECT REGION,
           CUSTOMER_NAME,
           ROUND(SUM(SALES),2) AS TOTAL_SALES
    FROM SUPERSTORE_RAW
    GROUP BY REGION, CUSTOMER_NAME
),
RANKED_CUSTOMERS AS
(
    SELECT REGION,
           CUSTOMER_NAME,
           TOTAL_SALES,
           RANK() OVER
           (
               PARTITION BY REGION
               ORDER BY TOTAL_SALES DESC
           ) AS SALES_RANK
    FROM CUSTOMER_REGION_SALES
)
SELECT REGION,
       CUSTOMER_NAME,
       TOTAL_SALES,
       SALES_RANK
FROM RANKED_CUSTOMERS
WHERE SALES_RANK <= 3
ORDER BY REGION, SALES_RANK;