Step 1 — Create the View
CREATE OR REPLACE VIEW CUSTOMER_SALES_VIEW AS
SELECT CUSTOMER_ID,
       CUSTOMER_NAME,
       SEGMENT,
       REGION,
       ROUND(SUM(SALES), 2) AS TOTAL_SALES,
       ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM SUPERSTORE_RAW
GROUP BY CUSTOMER_ID,
         CUSTOMER_NAME,
         SEGMENT,
         REGION;

Step 2 — Check the View
         
SELECT *
FROM CUSTOMER_SALES_VIEW;

Step 3 — Use the View for Top 10 Customers

SELECT *
FROM
(
    SELECT CUSTOMER_NAME,
           TOTAL_SALES,
           TOTAL_PROFIT
    FROM CUSTOMER_SALES_VIEW
    ORDER BY TOTAL_SALES DESC
)
WHERE ROWNUM <= 10;