SELECT PRODUCT_NAME,
       ROUND(SUM(SALES), 2) AS TOTAL_SALES,
       ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM SUPERSTORE_RAW
WHERE SUB_CATEGORY = 'Tables'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_PROFIT;