SELECT REGION,
       ROUND(SUM(SALES), 2) AS TOTAL_SALES,
       ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
       ROUND((SUM(PROFIT) / SUM(SALES)) * 100, 2) AS PROFIT_MARGIN
FROM SUPERSTORE_RAW
GROUP BY REGION
ORDER BY TOTAL_PROFIT DESC;