SELECT YEAR,
       TOTAL_SALES,
       ROUND(
           (TOTAL_SALES - LAG(TOTAL_SALES) OVER (ORDER BY YEAR))
           / LAG(TOTAL_SALES) OVER (ORDER BY YEAR) * 100,
           2
       ) AS YOY_GROWTH
FROM
(
    SELECT TO_CHAR(ORDER_DATE, 'YYYY') AS YEAR,
           ROUND(SUM(SALES), 2) AS TOTAL_SALES
    FROM SUPERSTORE_RAW
    GROUP BY TO_CHAR(ORDER_DATE, 'YYYY')
)
ORDER BY YEAR;