Step1: Calculate monthly sales:-

SELECT TO_CHAR(ORDER_DATE, 'YYYY-MM') AS MONTH,
       ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM SUPERSTORE_RAW
GROUP BY TO_CHAR(ORDER_DATE, 'YYYY-MM')
ORDER BY MONTH;

Step2: Monthly Sales Growth
SELECT MONTH,
       TOTAL_SALES,
       ROUND(
           (TOTAL_SALES - LAG(TOTAL_SALES) OVER (ORDER BY MONTH))
           / LAG(TOTAL_SALES) OVER (ORDER BY MONTH) * 100,
           2
       ) AS MOM_GROWTH
FROM
(
    SELECT TO_CHAR(ORDER_DATE, 'YYYY-MM') AS MONTH,
           ROUND(SUM(SALES), 2) AS TOTAL_SALES
    FROM SUPERSTORE_RAW
    GROUP BY TO_CHAR(ORDER_DATE, 'YYYY-MM')
)
ORDER BY MONTH;