SELECT
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    ROUND((SUM(PROFIT) / SUM(SALES)) * 100, 2) AS PROFIT_MARGIN
FROM SUPERSTORE_RAW;